Load Sloth

In [1]:
import slothpy as slt

Import additional packages

In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
a = np.array(1,2)

TypeError: Cannot interpret '2' as a data type

In [8]:
DyCo = slt.compound_from_orca(".", "Lorenzo_Co", "rot_orca", ".", "geom_rot.out")

Failed to create a HDF5 file from the ORCA output file or acces the exsiting one.


Exception: Error encountered while trying to create Compound: ValueError: Unable to create group (name already exists)

In [4]:
DyCo = slt.compound_from_orca(".", "Lorenzo_Co", "no_rot_orca", ".", "geom_no_rot.out")

In [5]:
DyCo = slt.compound_from_molcas(".", "Lorenzo_Co", "no_rot", ".", "no_rot_lorenzo_bas0")

In [6]:
DyCo = slt.compound_from_molcas(".", "Lorenzo_Co", "rot", ".", "rot_lorenzo_bas0_corr")

To obtain energies of spin-orbit states you can run:

In [5]:
DyCo = slt.compound_from_slt(".", "Lorenzo_Co")

In [7]:
DyCo.delete_group("bangi")

Exception reporting mode: Plain


SltFileError: 
SlothFileError, File "./Lorenzo_Co.slt", KeyError: "Couldn't delete link (callback link pointer is NULL (specified link may be '.' or not exist))" 
Failed to delete  "bangi" from the .slt file

In [6]:
DyCo.soc_energies_cm_1("no_rot_orca", 6)

array([0.00000000e+00, 5.98832958e-07, 2.81951501e+02, 2.81951502e+02,
       6.38418135e+02, 6.38418137e+02])

In [7]:
DyCo.soc_energies_cm_1("rot_orca", 6)

array([0.00000000e+00, 5.98832958e-07, 2.80524770e+02, 2.80524771e+02,
       6.35996686e+02, 6.35996686e+02])

In [9]:
g_tensor, axes = DyCo.calculate_g_tensor_and_axes_doublet("no_rot", [0,1])

In [10]:
g_tensor

array([[0.        , 0.04038119, 0.04124371, 9.60611473],
       [1.        , 3.235436  , 3.25472584, 4.59184894]])

In [11]:
axes

array([[[-1.46441413e-03, -9.99998804e-01, -4.97897718e-04],
        [-9.99998547e-01,  1.46484782e-03, -8.71785683e-04],
        [ 8.72513985e-04,  4.96620339e-04, -9.99999496e-01]],

       [[ 9.99986584e-01,  5.15451356e-03,  5.11678170e-04],
        [-5.15261737e-03,  9.99980099e-01, -3.64044545e-03],
        [-5.30432713e-04,  3.63776013e-03,  9.99993243e-01]]])

In [19]:
g_tensor, axes = DyCo.calculate_g_tensor_and_axes_doublet("no_rot_orca", [0,1])

In [20]:
g_tensor

array([[0.        , 0.01423292, 0.01447811, 9.83174038],
       [1.        , 1.73168107, 1.73300319, 5.57022942]])

In [21]:
axes

array([[[-0.37224021, -0.88033786,  0.29401102],
        [-0.81125841,  0.1547205 , -0.56384516],
        [ 0.4508847 , -0.44840475, -0.77177468]],

       [[-0.05773299,  0.95441606, -0.29284278],
        [-0.81457543,  0.12455323,  0.56652747],
        [ 0.57717742,  0.27124985,  0.77025304]]])

In [18]:
rot_trans = np.array([[-1.46441413e-03, -9.99998804e-01, -4.97897718e-04],
        [-9.99998547e-01,  1.46484782e-03, -8.71785683e-04],
        [ 8.72513985e-04,  4.96620339e-04, -9.99999496e-01]])

rot_trans = rot_trans.T

cfp_rot = DyCo.soc_crystal_field_parameters("rot", 0, 3, 2, rotation=rot_trans)

cfp_rot_cm_1 = np.array(cfp_rot)

for i in range(cfp_rot_cm_1.shape[0]):
    cfp_rot_cm_1 [i,2] = cfp_rot_cm_1 [i,2] * 219474.6
    
cfp_rot_cm_1



array([[ 0.00000000e+00,  0.00000000e+00,  1.21649818e+02],
       [ 2.00000000e+00, -2.00000000e+00,  1.20181834e-02],
       [ 2.00000000e+00, -1.00000000e+00, -1.33251285e-02],
       [ 2.00000000e+00,  0.00000000e+00, -9.93195554e+01],
       [ 2.00000000e+00,  1.00000000e+00, -1.86953589e-01],
       [ 2.00000000e+00,  2.00000000e+00,  1.66954110e+00]])

In [22]:
rot_trans = np.array([[-0.37224021, -0.88033786,  0.29401102],
        [-0.81125841,  0.1547205 , -0.56384516],
        [ 0.4508847 , -0.44840475, -0.77177468]])

rot_trans = rot_trans.T

cfp = DyCo.soc_crystal_field_parameters("no_rot_orca", 0, 3, 2, rotation=rot_trans)

cfp_cm_1 = np.array(cfp)

for i in range(cfp_cm_1 .shape[0]):
    cfp_cm_1 [i,2] = cfp_cm_1 [i,2] * 219474.6
    
cfp_cm_1

array([[ 0.00000000e+00,  0.00000000e+00,  1.40975751e+02],
       [ 2.00000000e+00, -2.00000000e+00,  9.62983959e-03],
       [ 2.00000000e+00, -1.00000000e+00,  7.24948022e-02],
       [ 2.00000000e+00,  0.00000000e+00, -1.15104507e+02],
       [ 2.00000000e+00,  1.00000000e+00,  5.64505494e-01],
       [ 2.00000000e+00,  2.00000000e+00,  6.81034331e-01]])

In [17]:
cfp = DyCo.soc_crystal_field_parameters("no_rot", 0, 3, 2)

cfp_cm_1 = np.array(cfp)

for i in range(cfp_cm_1 .shape[0]):
    cfp_cm_1 [i,2] = cfp_cm_1 [i,2] * 219474.6
    
cfp_cm_1

array([[  0.        ,   0.        , 121.65143446],
       [  2.        ,  -2.        ,  -8.33556005],
       [  2.        ,  -1.        , -93.81283247],
       [  2.        ,   0.        , -63.93488953],
       [  2.        ,   1.        , -51.60519097],
       [  2.        ,   2.        ,   4.83014611]])

In [60]:
for i in cfp:
    print(f"{i[0]} {i[1]} {i[2]* 219474.6}")

0 0 140.09167750067513
2 -2 -0.015022349505134178
2 -1 25.119260814974528
2 0 -94.1132191367354
2 1 59.96045646559236
2 2 -0.5034712790262911


In [17]:
for k in cfp_rot:
    print(f"{k[0]} {k[1]} {k[2]* 219474.6}")

0 0 139.99685848977649
2 -2 0.012002881468232581
2 -1 0.5185473915488832
2 0 -114.30381360695529
2 1 -0.13089081363393285
2 2 -0.6574555341124702


In [62]:
ito_soc_matrix_rot = DyCo.matrix_from_ito("kur")

In [10]:
ito_soc_matrix_no_rot = DyCo.matrix_from_ito("no_rot")

In [63]:
energies, eigenvectors = np.linalg.eigh(ito_soc_matrix_rot)
energies * 219474.6

array([ 11.8114666,  11.8114666, 268.3718884, 268.3718884])

In [12]:
energies, eigenvectors = np.linalg.eigh(ito_soc_matrix_no_rot)
energies * 219474.6

array([3.99221912e-07, 3.99221972e-07, 2.80183355e+02, 2.80183355e+02])

In [58]:
a = np.array([[ 5.78371953e-03,  9.99983087e-01, -6.12403982e-04],
        [ 9.99982768e-01, -5.78309945e-03,  1.00951341e-03],
        [ 1.00595475e-03, -6.18232171e-04, -9.99999303e-01]])
a = np.array([[ 0.2843829, -0.82284046, 0.49199588], [-0.41815955, -0.56825696, -0.70867949], [-0.86271024, 0.00419645, 0.50568116]])

np.linalg.det(a)

-1.0000000038630528

In [65]:
a = np.array(   [[22.101241999999999,        0.0000000000000000,        0.0000000000000000],     
  [-10.830011557286578,        19.265921924777000,        0.0000000000000000],     
  [-6.8320621260590041E-007,  -1.1678048477038437E-006,   39.144832999999970]])
b = a/3
b

array([[ 7.36708067e+00,  0.00000000e+00,  0.00000000e+00],
       [-3.61000385e+00,  6.42197397e+00,  0.00000000e+00],
       [-2.27735404e-07, -3.89268283e-07,  1.30482777e+01]])

In [66]:
for i in range(3):
    print(f'{b[i][0]:1.16f} {b[i][1]:1.16f} {b[i][2]:1.16f}')

7.3670806666666664 0.0000000000000000 0.0000000000000000
-3.6100038524288593 6.4219739749256668 0.0000000000000000
-0.0000002277354042 -0.0000003892682826 13.0482776666666567


In [4]:
DyCo.states_magnetic_momenta("rot_orca", 0)

[-1.91754977+2.25726549e-17j  1.91754977+2.45479487e-20j
  0.75328146+2.88337546e-17j -0.75328146+1.96870919e-16j
  1.54760317+3.30548204e-17j -1.54760317+8.10487732e-18j
  1.90604117-4.61216146e-17j -1.90604117-2.80921760e-21j
 -0.59915833+2.55038394e-19j  0.59915833-1.52188008e-16j
  0.56693268-9.72850204e-19j -0.56693268+3.49834636e-17j
 -0.0221493 -5.58686728e-19j  0.0221493 +1.43279956e-17j
 -0.24777712-7.21556807e-19j  0.24777712+4.57262167e-18j
  0.32969314-5.56850279e-17j -0.32969314-5.08104492e-17j
  2.04425199+1.20663594e-17j -2.044252  +1.07491788e-16j
 -2.3000098 -1.37636123e-17j  2.3000098 +7.78416218e-17j
  2.37382046+1.13753219e-18j -2.37382046-3.57004793e-17j
  0.00339845+3.64445224e-18j -0.00339845-3.96392387e-19j
 -0.00241055-2.50543102e-18j  0.00241055+3.51150431e-19j
  0.02258653+1.33789789e-19j -0.02258653+3.31120936e-19j
  0.05704445-9.75880805e-19j -0.05704445-2.00378601e-19j
 -0.14182832+1.12491054e-18j  0.14182832-1.57865176e-17j
  0.17664667-2.77666468e-19j -0

array([[ 4.29137544e-03, -4.29137780e-03,  7.50504201e-01,
        -7.50504195e-01,  9.87834558e-02, -9.87834599e-02,
         3.29647741e-05, -3.29648274e-05,  3.60985909e-02,
        -3.60985928e-02, -5.72934712e-02,  5.72934735e-02,
         1.80539665e-01, -1.80539665e-01,  5.01224806e-02,
        -5.01224802e-02, -3.87013527e-03,  3.87013128e-03,
         3.54796307e-02, -3.54796283e-02,  6.62599172e-02,
        -6.62599162e-02, -3.73130551e-02,  3.73130543e-02,
         4.41094528e-02, -4.41094524e-02,  4.13278696e-01,
        -4.13278697e-01, -6.80151601e-02,  6.80151631e-02,
         5.65225773e-01, -5.65225775e-01, -3.17480302e-01,
         3.17480302e-01,  2.55182889e-01, -2.55182890e-01,
        -2.54533010e-02,  2.54533030e-02, -9.37655127e-02,
         9.37655106e-02],
       [-3.84874288e-03,  3.84874341e-03, -2.59728593e-01,
         2.59728591e-01, -4.20926277e-01,  4.20926280e-01,
        -4.73498319e-03,  4.73498197e-03, -1.61383371e-01,
         1.61383366e-01,  1.68

In [21]:
fields_mag = np.linspace(0.1, 7, 70)
temperatures_mag = np.linspace(1.8, 2.5, 2)
temperatures_mag

array([1.8, 2.5])

In [22]:
%%time
magnetisation = DyCo.calculate_mth("rot_orca", 16, fields_mag, 5, temperatures_mag, 4, 2)

CPU times: user 250 ms, sys: 929 ms, total: 1.18 s
Wall time: 527 ms


In [24]:
fields_mag

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2, 1.3,
       1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6,
       2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9,
       4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1, 5.2,
       5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4, 6.5,
       6.6, 6.7, 6.8, 6.9, 7. ])

In [23]:
magnetisation

array([[0.29925057, 0.5869341 , 0.85350476, 1.09270093, 1.30176066,
        1.48082448, 1.63198725, 1.75838309, 1.86349277, 1.95070542,
        2.02308683, 2.08328788, 2.13353566, 2.17566687, 2.21117877,
        2.2412834 , 2.26695838, 2.28899126, 2.30801683, 2.32454758,
        2.33899847, 2.35170658, 2.36294681, 2.37294432, 2.38188437,
        2.38992009, 2.39717866, 2.4037662 , 2.40977172, 2.41527018,
        2.42032505, 2.42499027, 2.42931193, 2.43332953, 2.43707709,
        2.44058404, 2.4438759 , 2.44697491, 2.44990052, 2.45266976,
        2.45529764, 2.4577974 , 2.46018076, 2.46245813, 2.46463876,
        2.46673092, 2.468742  , 2.47067863, 2.47254678, 2.47435182,
        2.47609858, 2.47779145, 2.47943441, 2.48103106, 2.48258468,
        2.48409827, 2.48557456, 2.48701604, 2.488425  , 2.48980353,
        2.49115357, 2.49247688, 2.49377511, 2.49504974, 2.49630219,
        2.49753373, 2.49874557, 2.4999388 , 2.50111445, 2.50227349],
       [0.21638392, 0.42835242, 0.63190829, 0.8