Load Sloth

In [1]:
import slothpy as slt

Import additional packages

In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [31]:
DyCo = slt.compound_from_orca(".", "Lorenzo_Co", "rot_orca", ".", "rot.out")

In [32]:
DyCo = slt.compound_from_orca(".", "Lorenzo_Co", "no_rot_orca", ".", "no_rot.out")

In [3]:
DyCo = slt.compound_from_molcas(".", "Lorenzo_Co", "no_rot", ".", "no_rot_lorenzo_bas0")

In [4]:
DyCo = slt.compound_from_molcas(".", "Lorenzo_Co", "rot", ".", "rot_lorenzo_bas0")

To obtain energies of spin-orbit states you can run:

In [5]:
DyCo.soc_energies_cm_1("no_rot", 6)

array([0.00000000e+00, 4.75909676e-13, 2.43302869e+02, 2.43302869e+02,
       7.24048610e+02, 7.24048610e+02])

In [6]:
DyCo.soc_energies_cm_1("rot", 6)

array([0.00000000e+00, 9.51819353e-13, 2.43300128e+02, 2.43300128e+02,
       7.24054962e+02, 7.24054962e+02])

In [36]:
g_tensor, axes = DyCo.calculate_g_tensor_and_axes_doublet("rot_orca", [0,1])

In [37]:
g_tensor

array([[0.        , 0.01956045, 0.01998565, 9.79437324],
       [1.        , 3.70344884, 3.81823146, 7.83421777]])

In [38]:
axes

array([[[ 5.78371953e-03,  9.99983087e-01, -6.12403982e-04],
        [ 9.99982768e-01, -5.78309945e-03,  1.00951341e-03],
        [ 1.00595475e-03, -6.18232171e-04, -9.99999303e-01]],

       [[ 6.70292392e-02,  9.97566472e-01, -1.91889399e-02],
        [ 9.97357063e-01, -6.64499880e-02,  2.93817712e-02],
        [ 2.80351650e-02, -2.11076625e-02, -9.99384058e-01]]])

In [33]:
g_tensor, axes = DyCo.calculate_g_tensor_and_axes_doublet("no_rot_orca", [0,1])

In [34]:
g_tensor

array([[0.        , 0.0194008 , 0.01987514, 9.79540961],
       [1.        , 1.40597473, 1.44940627, 7.51010394]])

In [35]:
axes

array([[[-0.48926599, -0.82125664,  0.29352398],
        [-0.78215629,  0.26430542, -0.56424656],
        [ 0.38581125, -0.50564828, -0.7716667 ]],

       [[ 0.26188856,  0.92531054, -0.27425313],
        [-0.76217481,  0.37261996,  0.5293807 ],
        [ 0.59203373,  0.07039008,  0.80283329]]])

In [47]:
rot_trans = np.array([[ 5.78371953e-03,  9.99983087e-01, -6.12403982e-04],
        [ 9.99982768e-01, -5.78309945e-03,  1.00951341e-03],
        [ 1.00595475e-03, -6.18232171e-04, -9.99999303e-01]])

rot_trans = rot_trans.T

cfp_rot = DyCo.soc_crystal_field_parameters("rot_orca", 0, 3, 2, rotation = rot_trans)

cfp_rot_cm_1 = np.array(cfp_rot)

for i in range(cfp_rot_cm_1.shape[0]):
    cfp_rot_cm_1 [i,2] = cfp_rot_cm_1 [i,2] * 219474.6
    
cfp_rot_cm_1



array([[ 0.00000000e+00,  0.00000000e+00,  1.39996858e+02],
       [ 2.00000000e+00, -2.00000000e+00,  7.28796027e-03],
       [ 2.00000000e+00, -1.00000000e+00,  1.12140008e-02],
       [ 2.00000000e+00,  0.00000000e+00, -1.14304611e+02],
       [ 2.00000000e+00,  1.00000000e+00, -4.55544846e-01],
       [ 2.00000000e+00,  2.00000000e+00,  9.29927984e-01]])

In [48]:
rot_trans = np.array([[-0.48926599, -0.82125664,  0.29352398],
        [-0.78215629,  0.26430542, -0.56424656],
        [ 0.38581125, -0.50564828, -0.7716667 ]])

rot_trans = rot_trans.T

cfp = DyCo.soc_crystal_field_parameters("no_rot_orca", 0, 3, 2, rotation= rot_trans)

cfp_cm_1 = np.array(cfp)

for i in range(cfp_cm_1 .shape[0]):
    cfp_cm_1 [i,2] = cfp_cm_1 [i,2] * 219474.6
    
cfp_cm_1

array([[ 0.00000000e+00,  0.00000000e+00,  1.40091678e+02],
       [ 2.00000000e+00, -2.00000000e+00, -2.29647985e-01],
       [ 2.00000000e+00, -1.00000000e+00,  4.16093139e-02],
       [ 2.00000000e+00,  0.00000000e+00, -1.14382059e+02],
       [ 2.00000000e+00,  1.00000000e+00, -4.53890027e-01],
       [ 2.00000000e+00,  2.00000000e+00,  8.94165337e-01]])

In [17]:
cfp = DyCo.soc_crystal_field_parameters("no_rot", 0, 3, 2)

cfp_cm_1 = np.array(cfp)

for i in range(cfp_cm_1 .shape[0]):
    cfp_cm_1 [i,2] = cfp_cm_1 [i,2] * 219474.6
    
cfp_cm_1

array([[  0.        ,   0.        , 121.65143446],
       [  2.        ,  -2.        ,  -8.33556005],
       [  2.        ,  -1.        , -93.81283247],
       [  2.        ,   0.        , -63.93488953],
       [  2.        ,   1.        , -51.60519097],
       [  2.        ,   2.        ,   4.83014611]])

In [60]:
for i in cfp:
    print(f"{i[0]} {i[1]} {i[2]* 219474.6}")

0 0 140.09167750067513
2 -2 -0.015022349505134178
2 -1 25.119260814974528
2 0 -94.1132191367354
2 1 59.96045646559236
2 2 -0.5034712790262911


In [17]:
for k in cfp_rot:
    print(f"{k[0]} {k[1]} {k[2]* 219474.6}")

0 0 139.99685848977649
2 -2 0.012002881468232581
2 -1 0.5185473915488832
2 0 -114.30381360695529
2 1 -0.13089081363393285
2 2 -0.6574555341124702


In [62]:
ito_soc_matrix_rot = DyCo.matrix_from_ito("kur")

In [10]:
ito_soc_matrix_no_rot = DyCo.matrix_from_ito("no_rot")

In [63]:
energies, eigenvectors = np.linalg.eigh(ito_soc_matrix_rot)
energies * 219474.6

array([ 11.8114666,  11.8114666, 268.3718884, 268.3718884])

In [12]:
energies, eigenvectors = np.linalg.eigh(ito_soc_matrix_no_rot)
energies * 219474.6

array([3.99221912e-07, 3.99221972e-07, 2.80183355e+02, 2.80183355e+02])

In [58]:
a = np.array([[ 5.78371953e-03,  9.99983087e-01, -6.12403982e-04],
        [ 9.99982768e-01, -5.78309945e-03,  1.00951341e-03],
        [ 1.00595475e-03, -6.18232171e-04, -9.99999303e-01]])
a = np.array([[ 0.2843829, -0.82284046, 0.49199588], [-0.41815955, -0.56825696, -0.70867949], [-0.86271024, 0.00419645, 0.50568116]])

np.linalg.det(a)

-1.0000000038630528

In [65]:
a = np.array(   [[22.101241999999999,        0.0000000000000000,        0.0000000000000000],     
  [-10.830011557286578,        19.265921924777000,        0.0000000000000000],     
  [-6.8320621260590041E-007,  -1.1678048477038437E-006,   39.144832999999970]])
b = a/3
b

array([[ 7.36708067e+00,  0.00000000e+00,  0.00000000e+00],
       [-3.61000385e+00,  6.42197397e+00,  0.00000000e+00],
       [-2.27735404e-07, -3.89268283e-07,  1.30482777e+01]])

In [66]:
for i in range(3):
    print(f'{b[i][0]:1.16f} {b[i][1]:1.16f} {b[i][2]:1.16f}')

7.3670806666666664 0.0000000000000000 0.0000000000000000
-3.6100038524288593 6.4219739749256668 0.0000000000000000
-0.0000002277354042 -0.0000003892682826 13.0482776666666567
