# Moment siły ($\vec \tau$) i moment pędu ($\vec L$)

$$\Large \vec \tau = \vec r \times \vec F$$
$$\Large \vec L = \vec r \times \vec p$$

$$\Large  \vec r \times \vec V = rV\sin\theta = rV_{\perp}$$

<div style="text-align: center;">
  <img src="Presentations/Torque_animation.gif" width="30%" />
</div>

$$\Large  \frac{\mathrm{d}\vec{L}}{\mathrm{d}t} = \vec{r} \times \frac{\mathrm{d}\vec{p}}{\mathrm{d}t} + \frac{\mathrm{d}\vec{r}}{\mathrm{d}t} \times \vec{p} = \vec{r} \times \vec{F} + \vec{v} \times \vec{p} = \vec{\tau}$$

# Magnetyczny moment dipolowy ($\vec m$)

$$\Large \vec \tau = \vec m \times \vec B$$

<div style="text-align: center; font-size: 22px;">Moment magnetyczny pętli z prądem:</div>

$$\Large \vec m = I \cdot A \cdot \vec a $$

<div style="text-align: center;">
  <img src="Presentations/magnetic_moment.png" width="40%" />
</div>

<div style="text-align: center; font-size: 22px;">Dla jednej cząsteczki o ładunku q z prędkością v o masie m:</div>

$$\Large  I = \frac{q}{t} = \frac{q \cdot v}{2 \pi r}$$
$$\Large \vec m = \frac{q \cdot v \cdot \pi r^{2}}{2 \pi r} \cdot \frac{\vec r \times \vec v}{r \cdot v} \cdot \frac{m}{m} = \frac{q}{2m} \cdot \vec L$$

# Pętla z prądem w jednorodnym polu magnetycznym $\vec B$

<div style="text-align: center;">
  <img src="Presentations/torque_on_magnetic.png" width="50%" />
</div>

<div style="text-align: center; font-size: 22px;">Moment siły:</div>

$$\Large \vec \tau = \vec m \times \vec B$$

<div style="text-align: center; font-size: 22px;">Energia w polu:</div>

$$\Large E = \mathbf{- \vec m \cdot \vec B}$$


# Makroskopowa magnetyzacja ($\vec M$)

$$\Large \vec M_{V} = \frac{d\vec m}{dV}$$

$$\Large \vec m = \iiint \vec M_{V}\, dV$$

<div style="text-align: center;">
  <img src="Presentations/macroscopic_magnetisation.gif" width="35%" />
</div>

<div style="text-align: center; font-size: 22px;">Dla jednorodnych materiałów:</div>

$$\Large \vec M_{V} = \frac{\vec m}{V}$$

<div style="text-align: center; font-size: 22px;">Magnetyzacja molowa:</div>

$$\Large \vec{M}_{mol} = \frac{\vec{m}}{N_{mol}}$$

# Moment magnetyczny ($\vec \mu$) w mechanice kwantowej

<div style="text-align: center; font-size: 22px;">Magneton bohra:</div>

$$\Large \mu_B = \frac{e \hbar}{2 m_e}$$

<div style="text-align: center; font-size: 22px;">Orbitalny i spinowy moment magnetyczny:</div>

$$\Large \mu_L = -\mu_B \cdot \hat L$$

$$\Large \mu_S = -\mu_B \cdot g_e \cdot \hat S$$

$$\Large g_e = 2.002 319 304 362 56$$

<div style="text-align: center; font-size: 22px;">Jądrowy moment magnetyczny:</div>

$$\Large \mu_I = -\mu_B \cdot g_I \cdot \hat I$$

# Energia w polu magnetycznym - oddziaływanie Zeemana

$$\Large H_{Zeeman} = - \vec \mu \cdot \vec B = - (\vec \mu_S + \mu_L) \cdot \vec B$$

$$\Large H_{total}=H_{\text{ab initio}}+ H_{Zeeman}$$

$$\mathbf{\Large H_{total}=H_{\text{ab initio}}+\mu_B\left(g_e\vec{S}+\vec{L}\right)\cdot\vec{B}}$$

# SlothPy - [Dokumentacja](https://www.slothpy.org)

<div style="text-align: center;">
  <img src="Presentations/slothpy.png" width="50%" />
</div>

<div style="text-align: right; font-size: 18px;">Logo by Hubert Dziełak</div>


In [1]:
import slothpy as slt

                  ____  _       _   _     ____
                 / ___|| | ___ | |_| |__ |  _ \ _   _
                 \___ \| |/ _ \| __| '_ \| |_) | | | |
                  ___) | | (_) | |_| | | |  __/| |_| |
                 |____/|_|\___/ \__|_| |_|_|    \__, |
                                                |___/  by MTZ 

SlothPy Copyright (C) 2023 Mikolaj Tadeusz Zychowicz (MTZ).
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it.
The default is chosen to omit the tracebacks completely. To change it use slt.set_default_error_reporting_mode() method for the printing of tracebacks.
Turn on the SlothPy Monitor utility using slt.turn_on_monitor().
Exception reporting mode: Plain


In [2]:
Dy = slt.compound_from_molcas("./seminarium", "DyIrCN_Cl_bas2", "./seminarium", "Dy", "demo")

In [3]:
Dy

<SltCompound object for File './seminarium/Dy.slt'.>

In [4]:
print(Dy)

Compound from File: ./seminarium/Dy.slt with the following Groups/Datasets.
Group: demo | Description: Group containing relativistic SOC MOLCAS results. | Kind: MOLCAS | Precision: double | States: 2002 | Type: Hamiltonian
	SOC_ENERGIES | Description: Dataset containing SOC energies.
	SOC_LX | Description: Dataset containing the Lx matrix in the SOC basis.
	SOC_LY | Description: Dataset containing the Ly matrix in the SOC basis.
	SOC_LZ | Description: Dataset containing the Lz matrix in the SOC basis.
	SOC_SX | Description: Dataset containing the Sx matrix in the SOC basis.
	SOC_SY | Description: Dataset containing the Sy matrix in the SOC basis.
	SOC_SZ | Description: Dataset containing the Sz matrix in the SOC basis.


In [5]:
energies = Dy["demo"]["SOC_ENERGIES"][:16]
energies

array([-0.02887274, -0.02887274, -0.02798548, -0.02798548, -0.02744438,
       -0.02744438, -0.02729224, -0.02729224, -0.02704025, -0.02704025,
       -0.02693269, -0.02693269, -0.02660333, -0.02660333, -0.02648725,
       -0.02648725])

In [6]:
(energies - energies[0]) * 219474.6

array([ 0.00000000e+00, -3.65498631e-11,  1.94729779e+02,  1.94729779e+02,
        3.13488143e+02,  3.13488143e+02,  3.46879127e+02,  3.46879127e+02,
        4.02184999e+02,  4.02184999e+02,  4.25790818e+02,  4.25790818e+02,
        4.98077150e+02,  4.98077150e+02,  5.23554723e+02,  5.23554723e+02])

# Rozszczepienie Zeemana
$$\Large H_{total}=H_{\text{ab initio}}+\mu_B\left(g_e\vec{S}+\vec{L}\right)\cdot\vec{B}$$
$$\Large H_{total} \Psi = E(\vec B) \Psi$$
$$(U^{\dagger} H_{total} U = H_{diag})$$

In [7]:
zeeman = Dy.zeeman_splitting("demo", 16, [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], [[1,1,1]], slt_save = "moja_nazwa")
zeeman

array([[[-3.65498631e-11,  0.00000000e+00,  1.94729779e+02,
          1.94729779e+02,  3.13488143e+02,  3.13488143e+02,
          3.46879127e+02,  3.46879127e+02,  4.02184999e+02,
          4.02184999e+02,  4.25790818e+02,  4.25790818e+02,
          4.98077150e+02,  4.98077150e+02,  5.23554723e+02,
          5.23554723e+02],
        [-1.19922520e+00,  1.18234681e+00,  1.94377586e+02,
          1.95064961e+02,  3.09402837e+02,  3.17528996e+02,
          3.45444004e+02,  3.48274100e+02,  4.01769647e+02,
          4.02590203e+02,  4.24410114e+02,  4.27193618e+02,
          4.97502730e+02,  4.98508135e+02,  5.22456931e+02,
          5.24901188e+02],
        [-2.41775079e+00,  2.35027523e+00,  1.94006142e+02,
          1.95385720e+02,  3.05262102e+02,  3.21541341e+02,
          3.43966587e+02,  3.49625228e+02,  4.01362609e+02,
          4.02969559e+02,  4.23042176e+02,  4.28626194e+02,
          4.96835051e+02,  4.98741219e+02,  5.21651145e+02,
          5.26456662e+02],
        [-3.6553348

In [8]:
print(Dy)

Compound from File: ./seminarium/Dy.slt with the following Groups/Datasets.
Group: demo | Description: Group containing relativistic SOC MOLCAS results. | Kind: MOLCAS | Precision: double | States: 2002 | Type: Hamiltonian
	SOC_ENERGIES | Description: Dataset containing SOC energies.
	SOC_LX | Description: Dataset containing the Lx matrix in the SOC basis.
	SOC_LY | Description: Dataset containing the Ly matrix in the SOC basis.
	SOC_LZ | Description: Dataset containing the Lz matrix in the SOC basis.
	SOC_SX | Description: Dataset containing the Sx matrix in the SOC basis.
	SOC_SY | Description: Dataset containing the Sy matrix in the SOC basis.
	SOC_SZ | Description: Dataset containing the Sz matrix in the SOC basis.
Group: moja_nazwa | Description: Group containing Zeeman splitting calculated from group: demo. | Kind: directional | Precision: double | Type: Zeeman_splitting
	magnetic_fields | Description: Dataset containing magnetic field (T) values used in the simulation.
	orientat

In [9]:
Dy.plot_zeeman("moja_nazwa")

In [10]:
del Dy["moja_nazwa"]

In [11]:
print(Dy)

Compound from File: ./seminarium/Dy.slt with the following Groups/Datasets.
Group: demo | Description: Group containing relativistic SOC MOLCAS results. | Kind: MOLCAS | Precision: double | States: 2002 | Type: Hamiltonian
	SOC_ENERGIES | Description: Dataset containing SOC energies.
	SOC_LX | Description: Dataset containing the Lx matrix in the SOC basis.
	SOC_LY | Description: Dataset containing the Ly matrix in the SOC basis.
	SOC_LZ | Description: Dataset containing the Lz matrix in the SOC basis.
	SOC_SX | Description: Dataset containing the Sx matrix in the SOC basis.
	SOC_SY | Description: Dataset containing the Sy matrix in the SOC basis.
	SOC_SZ | Description: Dataset containing the Sz matrix in the SOC basis.


In [13]:
g_tensor, axes = Dy.calculate_g_tensor_and_axes_doublet("demo", [0,1,2,3,4,5,6,7])

In [14]:
g_tensor

array([[0.00000000e+00, 0.00000000e+00, 1.24623851e-02, 1.88860285e+01],
       [1.00000000e+00, 9.41979498e-02, 1.96721487e-01, 1.67497819e+01],
       [2.00000000e+00, 6.47355912e-01, 8.94074962e-01, 1.80190286e+01],
       [3.00000000e+00, 5.76866353e-01, 5.10060583e+00, 8.47383487e+00],
       [4.00000000e+00, 1.53357575e+00, 3.34715345e+00, 1.05073187e+01],
       [5.00000000e+00, 2.57385739e-01, 2.04641906e+00, 9.43761597e+00],
       [6.00000000e+00, 1.88646020e+00, 5.50463821e+00, 8.06474844e+00],
       [7.00000000e+00, 0.00000000e+00, 7.40836968e+00, 1.13829807e+01]])

In [15]:
axes

array([[[ 0.51093014, -0.00315344, -0.85961645],
        [-0.05803205,  0.99758544, -0.03815207],
        [ 0.85766116,  0.06937834,  0.50951347]],

       [[ 0.09525581,  0.61606871, -0.78191155],
        [-0.98660083,  0.16294679,  0.00819396],
        [ 0.13245802,  0.77065407,  0.62333553]],

       [[ 0.87031012,  0.34326201, -0.35317345],
        [ 0.0774113 , -0.80352608, -0.59021464],
        [-0.48638234,  0.48633016, -0.72588924]],

       [[ 0.10590738,  0.88854648, -0.44639531],
        [-0.79264608,  0.3464989 ,  0.50164798],
        [ 0.60041303,  0.30070527,  0.74099968]],

       [[-0.76593357, -0.39677052, -0.5058843 ],
        [-0.56406204,  0.03712843,  0.82489727],
        [-0.30851222,  0.91716664, -0.2522411 ]],

       [[ 0.56424625,  0.8228487 ,  0.06742535],
        [-0.79254965,  0.56272277, -0.23496412],
        [-0.2312817 ,  0.07913969,  0.96966267]],

       [[-0.55137699,  0.83114545, -0.07197675],
        [-0.66279989, -0.4888195 , -0.5672317 ],
        

In [16]:
zeeman = Dy.zeeman_splitting("demo", 16, [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], [axes[0,:,0], axes[0,:,1], axes[0,:,2]], slt_save = "moja_nazwa")
Dy.plot_zeeman("moja_nazwa")

In [17]:
# Skrypt z pliku

In [ ]:
# Stara wersja

In [ ]:
import slothpy as slt
Dy = slt.compound_from_molcas("./seminarium", "seminarium", "demo", "./seminarium", "DyIrCN_Cl_bas2")

In [18]:
g_tensor, axes = Dy.calculate_g_tensor_and_axes_doublet("demo", [i for i in range(8)], slt="demo")
decomposition = Dy.matrix_decomposition_in_z_pseudo_spin_basis("demo", "soc", "magnetic", 0, 15, axes[0].T, slt="demo")
energies = Dy.soc_energies_cm_1("demo", 16, slt="demo")
slt.exporting.table_energy_and_g(Dy, "demo", 7, krames=True, decomp="magnetic", i_last_composition=3, output_path="./seminarium", output_name="super_tabelka")

SlothPy message: Table was saved as super_tabelka in ./seminarium as docx file.


# Magnetyzacja mikroskopowo
$$\Large \vec M\left(\vec{B},T\right)=\frac{\sum_{i=1}^{n}{\vec \mu_i\left(\vec{B}\right)e^{-\frac{E_i\left(\vec{B}\right)}{k_BT}}}}{\sum_{i=1}^{n}e^{-\frac{E_i\left(\vec{B}\right)}{k_BT}}}=\frac{\sum_{i=1}^{n}{\vec \mu_i\left(\vec{B}\right)e^{-\frac{E_i\left(\vec{B}\right)}{k_BT}}}}{Z}$$

<div style="border:2px solid white; padding:10px;">
    
$$\Large H_{total}=H_{\text{ab initio}}+\mu_B\left(g_e\vec{S}+\vec{L}\right)\cdot\vec{B}$$

$$\Large H_{total} \Psi = E(\vec B) \Psi$$

$$\Large (U^{\dagger} H_{total} U = H_{diag})$$

</div>

<div style="text-align: center; font-size: 22px;">Transformujemy momenty do nowej bazy:</div>

$$\Large \mu\left(\vec{B}\right)=U^\dagger\vec\mu\left(\vec{B} = 0\right) U=U^\dagger\left(\mu_B\left(g_e\vec{S}+\vec{L}\right)\right)U$$

<div style="text-align: center; font-size: 22px;">Magnetyzacja proszkowa:</div>

$$\Large M({B}, T) = \frac{1}{2\pi} \int_{0}^{\pi} \sin\theta d\theta \int_{0}^{2\pi} d\phi \, M(\vec{B}\cdot \hat{n}, T) \cdot \hat{n}$$

In [4]:
from numpy import linspace
magnetisation = Dy.calculate_magnetisation("demo", linspace(0.01,8,64), 4, [2,4,6,8,10,20,30,50], states_cutoff=850, number_cpu =128, autotune=True)

KeyboardInterrupt: 

In [ ]:
from numpy import linspace
magnetisation = Dy.calculate_magnetisation("demo", linspace(0.01,8,64), 4, [2,4,6,8,10,20,30,50], 128, slt="demo")